### ISSUE TITLE
Visualize data

### ISSUE THREAD

**Issue by criptonauta** [jtlacci/cryptocurrency_correlator#1]
Hi!

Firstly, thanks for the program. Very useful.

Is it possible to add more altcoins? How to do?  --- UPDATE: Solved. Formula already adds +n

Thanks again

**Comment by criptonauta** [comment]
Also, I saw you hardcoded BTC calculations. In this way, can we change main coin (btc) for ETH, for instance?

**Comment by jtlacci** [comment]
Yah definitely,  
change:

## Creating a Bitcoin/USD datafram for converting coins to USD 
    coin_lookup('BTC',start,end,period,'USDT_')
to

    coin_lookup('ETH',start,end,period,'USDT_')

if you want to change all the coins to be in terms of ETH

or 
change:
## Currency Pairing
    pairing = 'BTC_'
to
   pairing = 'ETH_'

for prices on the Eth exchange, but their are not as many coins availible

**Comment by criptonauta** [comment]
Thanks
I did that. 

The strange thing is in USDT market.

if inverting BTC for USDT, it'll return all coins as -1
